### ISSUE TITLE
Extended Message Support for BGP (RFC 8654)

### ISSUE THREAD

**Issue by omuravskiy** [RIPE-NCC/bgpdump#1]
Now that the RFC is out it would be nice if bgpdump supports it.
Currently when parsing a file longer than 4k it is confused about the number of prefixes in the MP_UNREACH_NLRI attribute (for example), reporting

    [error] too many prefixes (20428 > 2050)

[long_withdrawal.gz](https://github.com/RIPE-NCC/bgpdump/files/4019264/long_withdrawal.gz)

**Comment by spakka** [comment]
Thanks for the report.

The 2050 limit (number of NLRIs that can easily fit in a 4k BGP update) needs revisited since the extended-messages RFC has been published.
It needs a bit of refactoring to move back to dynamic memory allocation in this function.

I'm not exactly sure about the reason for the confusion on the number of prefixes, but I will look at removing the problem first, and then see if it remains afterwards.

**Comment by spakka** [comment]
@omuravskiy Please could you test PR #8 and in particular, could you check the `test_expect/updates.long_withdrawal.gz.bgp.gz` and confirm that this matches what you expected in the `long_withdrawal.gz` test input file?

Thanks!

**Comment by omuravskiy** [comment]
@spakka Yes, the bgpdump of `test_data/updates.long_withdrawal.gz` looks correct. Thanks!

**Comment by spakka** [comment]
This has been fixed in PR #8
